version: '3.8'

services:
  # SQL Server Database
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mynorthwind-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - mynorthwind-network
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourStrong@Passw0rd -Q 'SELECT 1'"]
      interval: 30s
      timeout: 10s
      retries: 5

  # .NET 9 Web API
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mynorthwind-api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CONNECTION_SQL=Server=sqlserver;Database=Northwind;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=true;
      - SERVICE_ACCOUNT_PATH=/app/firebase/serviceAccountKey.json
    depends_on:
      sqlserver:
        condition: service_healthy
    volumes:
      - ./firebase:/app/firebase:ro
    networks:
      - mynorthwind-network
    restart: unless-stopped

  # Optional: SQL Server Management Studio (SSMS) alternative
  azure-data-studio:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: mynorthwind-ads
    ports:
      - "3000:3000"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
    depends_on:
      - sqlserver
    networks:
      - mynorthwind-network
    profiles:
      - tools

volumes:
  sqlserver_data:
    driver: local

networks:
  mynorthwind-network:
    driver: bridge 